version: '3.8'

services:
  web:
    build: 
      context: ./django
      dockerfile: Dockerfile
    command:  python3 demo/manage.py runserver
    volumes:
      - ./data/static:/home/app/web/staticfiles
    network_mode: "host"
    expose:
      - 8000
