version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command:  gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/demo/staticfiles

    image: belezyakov/django-cicd-demo:latest
    ports:
      - "8000:8000"
    networks:
      - django-cicd-demo

volumes:
  static_volume:

networks:
  django-cicd-demo:
