version: '3.8'

services:
  web:
    build: 
      context: ./django
      dockerfile: Dockerfile
    command:  gunicorn do-guide.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./data/static:/home/app/web/staticfiles
    expose:
      - 8000
    networks:
      - django-cicd-test

  nginx:
    build: ./nginx
    volumes:
      - ./data/static:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

networks:
  django-cicd-test:
