name: Django CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing-docker-compose-auto-deploy-digital-ocean: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose  -f docker-compose.yml up -d --build
      - name: Get docker logs
        run: docker ps
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to dockerhub
        run: |
          docker-compose push
      - name: stop containers
        run: docker-compose -f docker-compose.yml down --volumes
